export const ELEMENTOS = {
//Elementos de Login
    url: 'https://www.ze.delivery/', 
    BOTAOCOKIESS: '#onetrust-accept-btn-handler',
    BOTAOENTRAR:'#welcome-button-sign-in',
    BOTAOCRIARCONTA:'#create-account-link',
    NOME: '#signup-form-input-name',
    EMAIL:'#signup-form-input-email',
    SENHA:'#signup-form-input-password',
    TELEFONE: '#signup-form-input-phone',
    CPF:'#signup-form-input-document',
    IDADE: '#signup-form-input-age',
    TERMO:'#sign-up-form-input-terms',
    ERROSENHA:'#signup-form-input-password-error-message',
    ERROIDADE:'#signup-form-input-age-error-message',
    ERROCPF:'#signup-form-input-document-error-message',
    BOTAOCADASTRAR:'#signup-form-button-signup',
    HOME:'.css-1qn9swo-title', 
    ENTRAREMAIL:'#login-mail-input-email',  
    ENTRARSENHA:'#login-mail-input-password',
    BOTAOLOGAR:'#login-mail-button-sign-in',
    CONFIRMARIDADE:'#age-gate-button-yes',
    PESQUISAR:'#search-product-input',
    CONFIRMARPRODUTO: '.css-kzmtws-productCard',
    SALVARNOMEPRODUTO:'.css-aibq80-productTitle',
    SALVARPRECO:'.css-1jqrnd2-priceText',
    ADICIONARPRODUTO:'#add-product',
    NOMEPRODUTO:'.css-xsvw85-productTitle',
    PRECO:'.css-kj8j5x-priceText',
    ADICIONARNOCARRINHO:'#finish-order',
    NOMECARRINHO:':nth-child(1) > #product-name',
    PRECOCARRINHO:':nth-child(1) > #product-price',
}
    